### ISSUE TITLE
Error at vendor prefixes for @supports

### ISSUE THREAD

**Issue by radektuma** [MoOx/gulp-cssnext#12]
For the CSS:

`@supports (display: flex) `

are erroneously generated vendor prefixes:

`@supports ((display:-webkit-box)or(display:-webkit-flex)or(display:-moz-box)or(display:-ms-flexbox)or(display:flex))`

instead of the correct code:

```
@supports (display: -webkit-box) or
          (display: -webkit-flex) or
          (display: -moz-box) or
          (display: -ms-flexbox) or
          (display: flex)
```
          
Thank you
Radek Tuma

**Comment by MoOx** [comment]
This module is DEPRECATED. Use gulp-postcss instead. Thanks.
